config/routes.rb
Rails.application.routes.draw do
  root to: "products#new"
  resources :products, only: %i[index new create show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  # if image resize is need, add geometry: "sizexsize>" ( i.e 100x100> ) in styles
  has_attached_file :photo, styles: { avif: { format: :avif } }, processors: [:default, :avif], default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  before_save :floor_process_time

  private

  def floor_process_time
    return unless process_time

    self.process_time = process_time.floor(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.order(:photo_file_name)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)

    redirect_to product_path(@product)
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:photo, :photo_image_size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AfivExperiment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h3>Products#index</h3>

<%= link_to "New Product", new_product_path, class: 'btn btn-primary my-3' %>

<table class='table'>
  <thead>
    <th>Name</th>
    <th>Image Size</th>
    <th>Process Time(sec)</th>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.photo_file_name, product_path(product) %></td>
        <td><%= product.photo_image_size %></td>
        <td><%= product.process_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class='row justify-content-center my-5'>
  <h3>Create New Product With Photo</h3>
</div>

<div class= "row justify-content-center">
  <%= form_for @product, url: products_path, html: { multipart: true, class: 'col-3 bg-light' } do |form| %>
    <div class= "form-group my-3">
      <%= form.label :photo_image_size %>
      <%= form.select :photo_image_size, options_for_select(['400px', '600px', '800px', '1200px', '1600px']), {}, {class: 'form-control'} %>
    </div>
    <div class="form-group mb-3">
      <%= form.label :photo %>
      <%= form.file_field :photo, class: "form-control-file" %>
    </div>
    <div>
      <%= form.submit "Create", class: 'btn btn-primary mb-2'%>
    </div>
    <%= link_to 'Return to Product Index', products_path, class: "btn btn-sm btn-secondary my-3" %>
  <% end %>
</div>

app/views/products/show.html.erb
<h3>Product#show</h3>

<%= link_to 'Back to Index', products_path, class: 'btn btn-sm btn-secondary my-3' %>

<div>
  <%= "Photo Name: #{@product.photo_file_name}" %>
</div>
<div>
  <%= "Image Size: #{@product.photo_image_size}" %>
</div>
<div>
  <%= "Encode Process Time: #{@product.process_time} sec" %>
</div>

<table class='table my-3'>
  <thead>
    <th>#</th>
    <th>Original</th>
    <th>AVIF</th>
  </thead>
  
  <tbody>
    <tr>
      <td>Size</td>
      <td><%= File.size @product.photo.path%></td>
      <td><%= File.size @product.photo.path(:avif)%></td>
    </tr>
    <tr> 
      <td>Image</td>
      <td><%= image_tag @product.photo.url %></td>
      <td><%= image_tag @product.photo.url(:avif) %></td>
    </tr>
  </tbody>
</table>